services:
  backend:
    image: vehicle-recognition-backend:v1
    container_name: vehicle-recognition-backend
    environment:
      API_PREFIX: "/api/v1"
      CORS_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
      API_KEY: "d7d5b283df0ef5bf9b803b2eea2689bc7d1c60e562784ea40f35746ba2f60c23"
    ports:
      - "8008:8000"
    restart: unless-stopped
